chore: add basic type hints
guludo/venv-run pull request #12
Opened 2022-03-06 08:11 UTC by scop

This is correct after #11 has been applied, should be rebased on top of that re CHANGELOG.md anyway.

2022-03-07 10:09 UTC, guludo requested changes
Thanks for this. The only thing I think should be changed is the location of the import for `List`.

2022-03-07 10:09 UTC, guludo commented on src/venvrun.py
> +from typing import List
Could you please move this to the "from" import group?

2022-03-07 10:18 UTC, guludo commented on src/venvrun.py
> +from typing import List
Nice. Github allowed me to do it 🙂 .

2022-03-07 10:19 UTC, guludo approved these changes

2022-03-07 10:19 UTC, guludo commented
Hi, @scop. Thanks for this. I'll apply this now.

2022-03-07 10:19 UTC, merged

2022-03-07 19:57 UTC, scop commented
Thanks. An isort config could help with communicating the preferred import order/style -- in this particular case there were two possibilities and I guessed wrong :)

2022-03-14 11:08 UTC, guludo commented
Nice tip! Thanks. I had never heard of isort before.