Canonicalize and deduplicate guesses
guludo/venv-run pull request #9
Opened 2022-02-13 10:49 UTC by scop

So in (the rare) case we find multiple paths that point to the same venv, don't fail but just use it.

2022-02-19 15:25 UTC, guludo requested changes
Hello, @scop. Thanks for the patch.

We should have a test fixture that contains a symbolic link that points to an environment already detected. That would probably have to be done using temporary directories created at runtime because of differences between Unix and Windows regarding symbolic links.

Ah, and also: this new feature should be noted in the CHANGELOG, in the `Unreleased` section.

2022-02-27 11:09 UTC, scop commented
Done.

2022-02-28 21:57 UTC, guludo approved these changes

2022-02-28 21:58 UTC, guludo commented
Great! Thanks. I'll apply this now.

2022-02-28 21:58 UTC, merged